### ISSUE TITLE
🏝️ Feature Request: That I have infinite xp

### ISSUE THREAD

**Issue by reeboyty** [Blooket-Cheats/Blooket-Hacks#10]
### Contact Details

26hwhite@ga.hiltoncsd.net

### Gamemode

Global

### Requested function

Infinite XP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
I don’t really understand what you mean, could you explain in more detail?

**Comment by cph101** [comment]
> I don’t really understand what you mean, could you explain in more detail?
He means the pass thing

**Comment by CrazyH2** [comment]
> > I don’t really understand what you mean, could you explain in more detail?
> 
> He means the pass thing

???

**Comment by CrazyH2** [comment]
I'm confused!
