### ISSUE TITLE
🏝️ Feature Request: Resetting the daily max tokens and xp amount

### ISSUE THREAD

**Issue by sockmoney01** [Blooket-Cheats/Blooket-Hacks#105]
### Contact Details

Brennanmonster0321@outlook.com

### Gamemode

general

### Requested function

resetting the max daily amount or increasing t

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Read:
https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81
