### ISSUE TITLE
🏝️ Feature Request: iOS add tokens

### ISSUE THREAD

**Issue by Salemhamad123** [Blooket-Cheats/Blooket-Hacks#111]
### Contact Details

Salemhamad123

### Gamemode

Gold quest

### Requested function

That I see infinite tokens

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Salemhamad123** [comment]
My blooket name/email 
redgoose54/salemhamad1234@outlook.com

**Comment by cph101** [comment]
https://routinehub.co/shortcut/13646/

**Comment by cph101** [comment]
You asked for iOS, so I gave you a routinehub link. Clicking on “get shortcut” should open the shortcuts app if you have it installed
