### ISSUE TITLE
🏝️ Feature Request: Ban tool

### ISSUE THREAD

**Issue by Toxic996** [Blooket-Cheats/Blooket-Hacks#112]
### Contact Details

pvsparkman10@gmail.com

### Gamemode

Any

### Requested function

Kick selected player for 1 minute then after 1 minute able to join a code.

### Any existing code

```JavaScript
Sorry don't know any code
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Ok

**Comment by Toxic996** [comment]
you should also create a menu for the cheats too

**Comment by cph101** [comment]
Yeah

**Comment by cph101** [comment]
> yo you have a phone

Um, what 💀

**Comment by cph101** [comment]
Now that I think of it, actually when you (the host) kick a player, they can't join the same game indefinitely
