### ISSUE TITLE
🏝️ Feature Request: Kick all players

### ISSUE THREAD

**Issue by Toxic996** [Blooket-Cheats/Blooket-Hacks#114]
### Contact Details

prestonsz25@gmail.com

### Gamemode

Global

### Requested function

Kick everyone in the same code as you

### Any existing code

```JavaScript
No sorry.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81
