### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Fhejy** [Blooket-Cheats/Blooket-Hacks#116]
### Contact Details

lilg825@outlook.com

### Gamemode

The full hack

### Requested function

Have full control over the whole game, being able to ban people, change peoples names and so on whatever comes to the hack.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81
