### ISSUE TITLE
🏝️ Feature Request: blooket hacks

### ISSUE THREAD

**Issue by graysoneeee** [Blooket-Cheats/Blooket-Hacks#117]
### Contact Details

grayson.1811666@nv.ccsd.net

### Gamemode

blooket tokens

### Requested function

That I Inf Cash

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81
