### ISSUE TITLE
🪲 Bug: it just isnt working

### ISSUE THREAD

**Issue by BrentHilton** [Blooket-Cheats/Blooket-Hacks#12]
### Contact Details

gash@crime.su

### Hacks used

globals, some gamemodes like factory

### What happened?

any time i run the script in console it either;
a.) tells me that it didnt work
b.) tells me that it works, then does nothing

..yes i am on the right page (dashboard, play)

### What browsers are you seeing the problem on?

Chromium based

### Browser

chrome

### Relevant console errors

```JavaScript
VM48:5 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at <anonymous>:5:117
(anonymous) @ VM48:5
setInterval (async)
(anonymous) @ VM48:4
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
Hi, sorry this is happening.

We are aware of the hacks that say they don’t work and thats getting fixed. 

Would you mind telling us which hacks are say they work but they don’t.

We should fixing this as soon as possible!

Thanks in Advance, CrazyH

**Comment by BrentHilton** [comment]
> Hi, sorry this is happening.
> 
> We are aware of the hacks that say they don’t work and thats getting fixed.
> 
> Would you mind telling us which hacks are say they work but they don’t.
> 
> We should fixing this as soon as possible!
> 
> Thanks in Advance, CrazyH

so far, ive tried the majority of the global hacks, and all of the factory hacks. no luck

**Comment by CrazyH2** [comment]
Thanks i will have a look!

**Comment by CrazyH2** [comment]
We have fixed this issue please tell us if it happens again!

**Comment by BrentHilton** [comment]
been using for 3 weeks to a month and works like a charm!

**Comment by CrazyH2** [comment]
Thank you! We appreciate you telling us the hacks now work for you
