### ISSUE TITLE
🪲 Bug: 

### ISSUE THREAD

**Issue by Isaac11179** [Blooket-Cheats/Blooket-Hacks#124]
### Contact Details

2isaacpang@gmail.com

### Hacks used

Anti Ban Hack

### What happened?

how to apply this hack
i am already banned and tried this but to no avail

### What browsers are you seeing the problem on?

Chromium based

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
The anti ban hack is to stop yourself getting banned when you are not banned. not to ban you
