### ISSUE TITLE
🪲 Bug: 

### ISSUE THREAD

**Issue by AlbumanO** [Blooket-Cheats/Blooket-Hacks#126]
### Contact Details

albuman@outlook.com

### Hacks used

Global/Spoof Admin.js

### What happened?

Nothing happens (not sure if I'm using it wrong or smthing but nothing happens when I run it.

### What browsers are you seeing the problem on?

Opera / (GX)

### Relevant console errors

```JavaScript
Their was none.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
You are meant to run it on the stats page
