### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Tycho777** [Blooket-Cheats/Blooket-Hacks#128]
### Contact Details

Tycho2110@gmail.com

### Gamemode

ex. Global/Get All Blooks.js

### Requested function

I cant sell the blooks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
It doesn’t give you the blooks forever which is why you cant sell it
