### ISSUE TITLE
🏝️ Feature Request: Infinite spins on the coin wheel

### ISSUE THREAD

**Issue by Belphas** [Blooket-Cheats/Blooket-Hacks#14]
### Contact Details

liny02@uscstudents.org

### Gamemode

Global

### Requested function

spin the new daily wheel as many times as you want after a game

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JaydenTD500** [comment]
I don’t think this is posibble but i’ma try

**Comment by cph101** [comment]
@JaydenTD500 Can you accept our invite to join as a collaborator?

**Comment by cph101** [comment]
@JaydenTD500 [Click here](https://github.com/Blooket-Cheats/Blooket-Hacks/invitations)

**Comment by JaydenTD500** [comment]
> @JaydenTD500 [Click here](https://github.com/Blo%CE%BFket-Cheats/Blooket-Hacks/invitations)

Thanks!

**Comment by Cry0Sh1ft** [comment]
It might be possible if you find where the coin wheel is located in the code and ifits a class and has a method for spinning it find and use that method with a prompt that will ask the user how many times they want to spin it and use a loop that will count a variable up till it hits the amount of the amount of times they asked them to spin it

**Comment by VillainsRule4000** [comment]
not possible
a ton of people have already tried

**Comment by liam3242** [comment]
how do I find the code for blooket games and global

**Comment by Cry0Sh1ft** [comment]
@liam3242  wdym by that
