### ISSUE TITLE
Reporting Readme Stealing

### ISSUE THREAD

**Issue by VillainsRule4000** [Blooket-Cheats/Blooket-Hacks#15]
### What happened?

https://github.com/monkxy/blooket-hacks
Jude is stealing your README styles

### What browsers are you seeing the problem on?

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
Whats your discord? And are you in the discord server?

**Comment by VillainsRule4000** [comment]
Death#5368

**Comment by CrazyH2** [comment]
Role has been added!

**Comment by VillainsRule4000** [comment]
> Role has been added!

y'all make nice hacks
yuo should enable blank issues for stuff like this though

**Comment by CrazyH2** [comment]
ok I will add that

**Comment by cph101** [comment]
Done
