### ISSUE TITLE
🪲 Bug: Monster Brawl hacks not working

### ISSUE THREAD

**Issue by AdrienHacker** [Blooket-Cheats/Blooket-Hacks#29]
### Contact Details

amouzon29@tfs.ca

### Hacks used

Blooket-Hacks/Monster Brawl/

### What happened?

I put in the code and nothing happens.

### What browsers are you seeing the problem on?

Other

### Relevant console errors

```JavaScript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Thank you for reporting this! We will have a look and fix this as soon as we can.

Can I just confirm that none of the hacks in the “Monster Brawl” directory are working? (I assume so)

**Comment by CrazyH2** [comment]
Please tell more detail eg what told you that it didn’t work! Thx
