### ISSUE TITLE
🏝️ Feature Request: maybe could you add a working javascript version i do this on a school computer and the inspect tool is blocked.

### ISSUE THREAD

**Issue by poooooooper** [Blooket-Cheats/Blooket-Hacks#3]
### Contact Details

topgpoopy@gmail.com

### Gamemode

blooket

### Requested function

the regular hacks work with javascript

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by poooooooper** [comment]
also i meant like a bookmarklet

**Comment by CrazyH2** [comment]
Ok, I will do that but it will be on a website and you will need to just drag the hack name to your bookmarks bar.

**Comment by CrazyH2** [comment]
Should be done by Saturday if thats ok?

**Comment by cph101** [comment]
@poooooooper They will be located in a branch called ‘bookmarklets’.
If you din’t know how to get there, select it from the place where it says ‘main’, or follow [this link](https://github.com/Blooket-Cheats/Blooket-Hacks/tree/bookmarklets)

**Comment by cph101** [comment]
- [x] Done

**Comment by cph101** [comment]
✅ Done

**Comment by poooooooper** [comment]
thank you!! sorry i haven't replied haven't checked my email in a while i really appreciate your work i mentioned you to my friends and hoping they star your project!😁
