### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by jacobbsjreeeee** [Blooket-Cheats/Blooket-Hacks#31]
### Contact Details

jacob.catlett873@cfbmail.com

### Gamemode

all game modes

### Requested function

I want all blooks 1 million blooket tokens

### Any existing code

```JavaScript
pls
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
This is impossible due to server side limits. 

If you want to be really specific, it is technically not impossible if we were to hack their servers, but that would be illegal and beyond my expertise. 🤪

We also wish we could do this 😭
