### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by XXXBruhx1** [Blooket-Cheats/Blooket-Hacks#34]
### Contact Details

2029dgreene@louisiana.k12.mo.us

### Gamemode

crypto hack

### Requested function

that i have infinite XP

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
OK I'll see if I can do that for you today :) If I remember correctly, though, the Crypto Hack currency is Bitcoin not XP. Can you confirm that this is what you mean?

**Comment by Believaboat** [comment]
any reason not to manually change the crypto?

**Comment by CrazyH2** [comment]
### This: [CLICK THIS TEXT](https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crypto%20Hack/Set%20crypto.js)
This will ask how much crypto you want and just put **`999999`** in and it should be as close as infinite as possible!

**Comment by Believaboat** [comment]
u should close it as `not done`

**Comment by XXXBruhx1** [comment]
Can you make a JavaScript I’m kicked off my computer and my school is gay

**Comment by Believaboat** [comment]
wait your school is in a homosexual relationship?

**Comment by XXXBruhx1** [comment]
On Wed, Mar 1, 2023 at 11:54 AM Boat ***@***.***> wrote: they
blocked everything that shit is gay

**Comment by Believaboat** [comment]
i dont think thats homosexual, i think thats policy

**Comment by cph101** [comment]
It is homo | school policy is ****
