### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Minesraft2** [Blooket-Cheats/Blooket-Hacks#35]
The following scripts have been found to be stolen from one of my repositories. Please remove them or I'll have to submit a DMCA to take them down.

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Blook%20Rush/Set%20blooks.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Blook%20Rush/Set%20defense.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Cafe/Infinite%20food.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Cafe/Set%20cash.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crazy%20Kingdom/Max%20stats.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crazy%20Kingdom/Set%20guests.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crazy%20Kingdom/Skip%20guest.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crypto%20Hack/Block%20hacks.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crypto%20Hack/Set%20crypto.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Crypto%20Hack/Set%20password.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Deceptive%20Dinos/Set%20fossils.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Fishing%20Frenzy/Set%20lure.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Fishing%20Frenzy/Set%20weight.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/All%20Answers%20Correct.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Anti%20Ban.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Highlight%20Answers.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Random%20Name%20Bypass.js
axios part of https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Global/Sell%20Dupes.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Gold%20Quest/See%20through%20chests.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Monster%20Brawl/Remove%20Obstacles.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Racing/Instant%20win.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Santa's%20Workshop/Prevent%20distractions.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20Defense/Clear%20enemies.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20Defense/INFINITE%20cash.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20Defense/Max%20out%20towers.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20Defense/Set%20cash.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20Defense/Set%20round.js

https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20of%20Doom/Lower%20enemy%20stats.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20of%20Doom/Max%20player%20stats.js
https://github.com/Blooket-Cheats/Blooket-Hacks/blob/main/Tower%20of%20Doom/Set%20coins.js

**Comment by cph101** [comment]
We may have taken code from your files and we apologise for that, but I am certain that less than a third of the files you mentioned actually use code from one of your repos.

**Comment by Believaboat** [comment]
> We may have taken code from your files and we apologise for that, but I am certain that less than a third of the files you mentioned actually use code from one of your repos.

doesnt really matter. his code was used, you have to remove them lol

**Comment by Minesraft2** [comment]
> We may have taken code from your files and we apologise for that, but I am certain that less than a third of the files you mentioned actually use code from one of your repos.

Most use code from therealgliz/blooket-hacks, which were all created by me

**Comment by cph101** [comment]
That is obfuscated tho…?

**Comment by Minesraft2** [comment]
They're not?

**Comment by Minesraft2** [comment]
We can handle this

> why did you delete my comment?

**Comment by Believaboat** [comment]
alright

> We can handle this
> 
> > why did you delete my comment?

**Comment by cph101** [comment]
> why did you delete my comment?

Because this is just The owners and @Minesraft2 
Pls dont disturb us we are trying to have a sensible conversation

**Comment by cph101** [comment]
> They're not?

Last time i checked.. but sure - if that’s what you want

we’re happy to give you no 1 credit if we can keep them up

**Comment by Minesraft2** [comment]
You'll either have to take them down or rewrite them to not use our react method

**Comment by cph101** [comment]
Is that all we have to do?

> … or rewrite them to not use our react method

**Comment by cph101** [comment]
OK so it’s fine If I change it to use the `stateNode` directly?

**Comment by Minesraft2** [comment]
You can't use `Object.values(document.querySelector("#app > div > div"))` that was made by me with help from darklord

**Comment by cph101** [comment]
Right so then `Object.values(document.getElementById("app").children[0].children[0])`

is that different enough?

**Comment by Minesraft2** [comment]
That's pretty much the exact same thing

**Comment by Minesraft2** [comment]
I didn't list every single react script just reuse those

**Comment by cph101** [comment]
So what do you suggest then there literally isnt anything else

**Comment by CrazyH2** [comment]
How about this? `Object.values(document.getElementsByTagName("body")[0].children[0].children[0].children[0])[1].children[1]._owner.stateNode.state`

**Comment by Minesraft2** [comment]
You guys know there's more ways to get to the stateNode than that one element right

**Comment by CrazyH2** [comment]
What do you mean?

**Comment by CrazyH2** [comment]
their is multiple elements that work?

**Comment by Minesraft2** [comment]
Literally any element would work

**Comment by Minesraft2** [comment]
And there's a bunch of methods to get stateNode that don't even use Object.values

**Comment by CrazyH2** [comment]
so this? `Object.values(document.getElementsByClassName("arts__body___3acI_-camelCase")[0])[1].children[1]._owner.stateNode.state`

**Comment by CrazyH2** [comment]
> And there's a bunch of methods to get stateNode that don't even use Object.values

How? not using object.values

**Comment by cph101** [comment]
We did not even get it from your repo!

Do you think that I would go copying your messy gibberish instead of just copying [this](https://github.com/LionsRH555/Blooket-Hack/blob/main/Get%20All%20Blooks%20on%20Blook%20Page)?

**Comment by CrazyH2** [comment]
or this maybe?

```
function getStateNode() {
    var path = document.getElementsByTagName("body")[0].children[0].children[0].children[0];
    var getObj = Object;
    return getObj.values(path)[1].children[1]._owner.stateNode;
};
```

**Comment by CrazyH2** [comment]
I guess its ok then?

**Comment by CrazyH2** [comment]
please respond?

**Comment by Minesraft2** [comment]
No, it is not ok then

**Comment by CrazyH2** [comment]
Well to be honest you don’t own js and it doesn’t look the same so i am doing it!

**Comment by Minesraft2** [comment]
The first couple lines of each script looks taken straight from therealgliz

**Comment by Minesraft2** [comment]
And it doesn't really matter

**Comment by CrazyH2** [comment]
You don’t own what it does you own how to do it and i have changed it to the point where nearly everything is different

**Comment by Minesraft2** [comment]
Github has ways to resolve this

**Comment by CrazyH2** [comment]
So your the real gliz and got a dmca yourself so don’t send me one or i will..

**Comment by Minesraft2** [comment]
I'm not gliz, my work is on his repo

**Comment by CrazyH2** [comment]
How come yours is obsficated and his is not?

**Comment by Minesraft2** [comment]
I have a folder for obfuscated scripts for people who want to copy it into a bookmark. I also have a folder with unobfuscated scripts

**Comment by CrazyH2** [comment]
That was put there after he put his up

**Comment by Minesraft2** [comment]
That's because gliz lost access to the account. And there's no use crying over spilled milk, dmca is sent, I even provided that one comment of yours blatantly stating you're trying to make it look different to avoid it. It is what it is, I'll now be unsubscribing to this thread and waiting for it to be processed.

**Comment by GooseterV** [comment]
we may not own JavaScript, but we own copyright to our code as of the DMCA, and even if you "credit us", you're still breaking the terms of the stewart private license which licenses our code. this isnt the first time we've submitted a dmca request, and yes github WILL take action.

**Comment by GooseterV** [comment]
if the code is on github, the owner of the codebase which was originally made by them and licensed

**Comment by GooseterV** [comment]
github restricts us full copyright over our own licensed and or unlicensed code.
