### ISSUE TITLE
School Chromebook non compatible 

### ISSUE THREAD

**Issue by winterminero4YT** [Blooket-Cheats/Blooket-Hacks#38]
### Contact Details

winterminero4@gmail.com

### Hacks used

Cant use any

### What happened?

our school has made it impossible to use bookmarklets and even open the inspect element.

I recommend maybe making and html version of the cheats or something like that

kindest regards 

### What browsers are you seeing the problem on?

Other

### Browser

Google

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Believaboat** [comment]
not possible to fix

**Comment by winterminero4YT** [comment]
oh ok thanks

**Comment by CrazyH2** [comment]
I can try but that would be in quite a while.

**Comment by Believaboat** [comment]
> I can try but that would be in quite a while.

if the bookmarklet version doesn't work, Javascript is blocked, and you can't unblock Javascript
