### ISSUE TITLE
🏝️ Feature Request: BLOOKET HACK

### ISSUE THREAD

**Issue by BOSSDOG42611** [Blooket-Cheats/Blooket-Hacks#43]
### Contact Details

S29-bcor470@w-usd.org

### Gamemode

Blooket

### Requested function

Infinity coins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
How many times do we need to fricking tell people this:

GIVING YOU INFINITE TOKENS IS IMPOSSIBLE!!!!!


we wish we could, but we cant.
