### ISSUE TITLE
🪲 Bug: Add reward does not work

### ISSUE THREAD

**Issue by AdrienHacker** [Blooket-Cheats/Blooket-Hacks#44]
### Contact Details

amouzon29@tfs.ca

### Hacks used

ex. Global/Add Rewards.js

### What happened?

![image](https://user-images.githubusercontent.com/115197019/221926088-ce74c079-2242-4843-9031-6197c24cf78c.png)

I have not collected any tokens or EX yet.

### What browsers are you seeing the problem on?

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Thanks for the bug report! We will have a look and try to see if we can fix this

**Comment by CrazyH2** [comment]
You can only run the script once and the alert you are talking about tells you if you are able to earn any tokens that day as their is a token limit.
