### ISSUE TITLE
🏝️ Feature Request: Infinite daily tokens

### ISSUE THREAD

**Issue by AdrienHacker** [Blooket-Cheats/Blooket-Hacks#45]
### Contact Details

amouzon29@tfs.ca

### Gamemode

ex. Infinite Daily Tokens

### Requested function

Infinite daily tokens

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
How many times can we f*cking tell people this!!!!!!

that is impossible

**Comment by AdrienHacker** [comment]
Have you tried?

**Comment by CrazyH2** [comment]
Blooket have a limit oer day

**Comment by AdrienHacker** [comment]
Copy its code

**Comment by cph101** [comment]
It’s server side

**Comment by AdrienHacker** [comment]
Oh  Sent from Mail for Windows From: cph101Sent: March 6, 2023 10:15 AMTo: Blooket-Cheats/Blooket-HacksCc: AdrienHacker; AuthorSubject: Re: [Blooket-Cheats/Blooket-Hacks] 🏝️ Feature Request: Infinite daily tokens (Issue #45) It’s server side—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
