### ISSUE TITLE
🏝️ Feature Request: Can you and your team make a hack for crypto hack where you can set other people's crypto

### ISSUE THREAD

**Issue by toastedANDroasted** [Blooket-Cheats/Blooket-Hacks#46]
### Contact Details

jacksonayden832@gmail.com

### Gamemode

crypto hack 

### Requested function

That i can set others crypto 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Can’t do this mate sorry. It’s because the data is stored on their side if you want to know
