### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by kingwoodb9987** [Blooket-Cheats/Blooket-Hacks#47]
### Contact Details

damarrionneal@gmail.com

### Gamemode

gold quest

### Requested function

every question right

### Any existing code

```JavaScript
30572021
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
This is already existent as a global hack (every gamemode). Find it at Global/All Answers Correct.js
