### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by UnspokenLife** [Blooket-Cheats/Blooket-Hacks#50]
### Contact Details

watersriptide@gmail.com

### Gamemode

Global

### Requested function

On iPad or phone

### Any existing code

```JavaScript
No I’m bad at coding
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Click “Switch to Bookmarklet mode in the readme”
