### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by hiddensea** [Blooket-Cheats/Blooket-Hacks#52]
### Contact Details

theoralph09@gmail.com

### Gamemode

Global

### Requested function

Mod Menu

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
This is already an issue. Please can you make sure you are not creating duplicate issues.

(See [this](https://github.com/Blooket-Cheats/Blooket-Hacks/issues/9))
