### ISSUE TITLE
Take this down

### ISSUE THREAD

**Issue by Thing3487** [Blooket-Cheats/Blooket-Hacks#56]
Not ur code. You  won’t want too know what my main account is named.

**Comment by Thing3487** [comment]
Nice try with [this](https://github.com/Blooket-Cheats/Blooket-Hacks/issues/36)

**Comment by Thing3487** [comment]
and [this](https://github.com/Blooket-Cheats/Blooket-Hacks/blob/experimental/Global/GUI.js)

**Comment by Thing3487** [comment]
@CrazyH2 @cph101

**Comment by cph101** [comment]
Well it’s your fault you were looking at the EXPERIMENTAL branch. If you want to go make people’s live hard ( for example ours ), I don’t care, and I could phrase that a ton stronger if you want me to.
