### ISSUE TITLE
That more like it!

### ISSUE THREAD

**Issue by ThingsAccount2again** [Blooket-Cheats/Blooket-Hacks#66]
We will  keep  monitoring this repo

**Comment by ThingsAccount2again** [comment]
Who will be monitoring? Minesraft2, Me, VillainsRule, Greenlio, fowntain, and s-r-y

**Comment by ThingsAccount2again** [comment]
So don’t even THINK about reuploading code

**Comment by cph101** [comment]
So you’re gliz then…?
