### ISSUE TITLE
hacks

### ISSUE THREAD

**Issue by jakelester12** [Blooket-Cheats/Blooket-Hacks#68]
### Contact Details

jakelester939@yahoo.com

### Gamemode

ex.bluck rush

### Requested function

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

### Any existing code

```JavaScript
n
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jakelester12** [comment]
its nioce

**Comment by CrazyH2** [comment]
I dont really undetstand what you mean
