### ISSUE TITLE
🏝️ Feature Request: 1000 gold 

### ISSUE THREAD

**Issue by Jorgefabi** [Blooket-Cheats/Blooket-Hacks#69]
### Contact Details

ashokafabian@gmail.com

### Gamemode

Gold quest 

### Requested function

That I hav infinite gold

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
We cant give infinite of anything

**Comment by CrazyH2** [comment]
Check github repo and there is a script in gold quest folder that is called setgold just use that
