### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Judah7209** [Blooket-Cheats/Blooket-Hacks#71]
### Contact Details

judah7209@trussvillecityschools.org

### Gamemode

all gamemodes (console mode)

### Requested function

That I have all the blooks and all the other hacks

### Any existing code

```JavaScript
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrazyH2** [comment]
Check github repo files
