### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Develpor344** [Blooket-Cheats/Blooket-Hacks#72]
### Contact Details

e.alhashemi@hotmail.com

### Gamemode

All

### Requested function

that I can see the correct answers and etc

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Develpor344** [comment]
btw all gamemodes I want do this with

**Comment by cph101** [comment]
This already a hack. Use your eyes or a screen reader.
