### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by noaholiversmith** [Blooket-Cheats/Blooket-Hacks#82]
### Contact Details

bigboichonkus237@gmail.com

### Gamemode

Global/Not in a gamemode section

### Requested function

A gui javascript, something like what minesraft2 had.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Okay, but you obviously haven’t read [this](https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81)
