### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by cadenhkang** [Blooket-Cheats/Blooket-Hacks#86]
### Contact Details

cadenhkang@gmail.com

### Gamemode

all

### Requested function

infinite gold

### Any existing code

```JavaScript
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
https://github.com/Blooket-Cheats/Blooket-Hacks/issues/81
