### ISSUE TITLE
🏝️ Feature Request: Luck booster

### ISSUE THREAD

**Issue by ANormalOhioan** [Blooket-Cheats/Blooket-Hacks#93]
### Contact Details

3070199@lfschools.net

### Gamemode

Global

### Requested function

It increases luck for legendaries and chromas (its fine if its on pc only like inspect)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
Truly, this is a great idea, and we wish this is possible, but unfortunately, how blooket works, is it sends a request to blooket’s servers with the pack’s name and your account name, not what blook to unlock. The server then decides what blook to give, and sends this back to us, so unless we get into blooket’s server, which is technically illegal, we can’t do this :(
