### ISSUE TITLE
🏝️ Feature Request: 

### ISSUE THREAD

**Issue by Men345** [Blooket-Cheats/Blooket-Hacks#99]
### Contact Details

27lordsk@ttsdstudents.org

### Gamemode

Gold quest

### Requested function

Infinite gold

### Any existing code

```JavaScript
I don’t sorry
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cph101** [comment]
This is already a hack, please check before creating an issue.
